services:
    yahoo_weather_parser:
        class: Nfq\WeatherBundle\YahooWeatherParser
        arguments: []

    yahoo_weather:
        class: Nfq\WeatherBundle\YahooWeatherService
        arguments: ['@yahoo_weather_parser', '@buzz']

    nfq_weather:
        class: Nfq\WeatherBundle\WeatherLoader
        arguments: ['@yahoo_weather']

