services:
    location:
        class: Nfq\WeatherBundle\Location
        arguments: [longitude, latitude]

    http_client:
        class: Nfq\WeatherBundle\HttpClient
        arguments: ['@buzz']

    yahoo_weather_parser:
        class: Nfq\WeatherBundle\YahooWeatherParser
        arguments: []

    yahoo_weather:
        class: Nfq\WeatherBundle\YahooWeatherService
        arguments: ['@yahoo_weather_parser', '@http_client']

    nfq_weather:
        class: Nfq\WeatherBundle\WeatherLoader
        arguments: ['@yahoo_weather']

